name: Plante
description: App for Plante Project
publish_to: "none"
version: 1.0.0+3
environment:
  sdk: ">=2.12.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.0"
  flutter_native_splash: "^1.2.0"

dependency_overrides:
  args: "^2.1.1"

flutter:
  uses-material-design: true
