
platform :ios do
  
  desc "Get certificates"
  lane :certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.plante.app',
      readonly: true
    )
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.plante.app',
      force_for_new_devices: true,
      readonly: false
    )
  end

  desc "deploy"
  lane :deploy do
    setup_travis
    sync_code_signing(
      type: "appstore",
      app_identifier: 'com.plante.app',
      readonly: true
    )
    build_app
    app_store_connect_api_key(
      is_key_content_base64: true,
      in_house: false, 
    )
    upload_to_testflight
  end
end
